# Numpy

***Topics Covered***


*   1D Arrays
*   Multidimensional Array
*   Array Reshaping
*   Flatten
*   Numpy Operations & more




In [ ]:
import numpy as np

In [ ]:
listpython = [1, 2, 3]
listpython

[1, 2, 3]

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
a * b

array([ 4, 10, 18])

In [ ]:
[5] * [3]

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
np.array([5]) * np.array([3])

array([15])

In [ ]:
c = np.arange(1, 10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d = np.arange(1, 10, 0.1)
d

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
lista = [1,2,3]
listb = [4,5,6]
lista + listb

[1, 2, 3, 4, 5, 6]

In [ ]:
arrayc = np.array(lista+listb)
arrayc

array([1, 2, 3, 4, 5, 6])

In [ ]:
e = np.array([1, 4, 9, 16])
sqrte = np.sqrt(e)

In [ ]:
e

array([ 1,  4,  9, 16])

In [ ]:
sqrte

array([1., 2., 3., 4.])

In [ ]:
e.dtype

dtype('int64')

In [ ]:
sqrte.dtype

dtype('float64')

In [ ]:
f = np.array([1, 4, 9, 16], float)
f

array([ 1.,  4.,  9., 16.])

In [ ]:
f.dtype

dtype('float64')

In [ ]:
g = np.sqrt(f).astype('int32')
g

array([1, 2, 3, 4], dtype=int32)

In [ ]:
g.dtype

dtype('int32')

In [ ]:
h = np.array([[1,2], [3,4], [5,6]])
h

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
h.shape

(3, 2)

In [ ]:
k = np.array([[1,2,3], [4,5,6]])
k

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
k.shape

(2, 3)

In [ ]:
nprange = np.arange(1, 10)
nprange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
reshaped = nprange.reshape((3, 3))
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ab = np.arange(1, 11)
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ab[5]

6

In [ ]:
reshaped_output = ab.reshape((5, 2))
reshaped_output

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
reshaped_output[3]

array([7, 8])

In [ ]:
reshaped_output[3][0]

7

In [ ]:
reshaped_output.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Flatten in NumPy**


In [ ]:
reshaped.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**Transpose Matrix**

In [ ]:
reshaped.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

In [ ]:
c

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.zeros_like(reshaped)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros_like(reshaped_output)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
reshaped_output

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Pandas ( sneak-peek :D )

In [ ]:
import pandas as pd

In [ ]:
ourdata = pd.read_csv('pandas-intro.csv')

In [ ]:
ourdata

Name  Age Campus
0      Sajon   99   RUET
1      Anjan    5    CoU
2  Shahjalal    5    CoU
3     Tousif    5    CoU
4    Sayedul    5    CoU

In [ ]:
ourdata['Age']

0    99
1     5
2     5
3     5
4     5
Name: Age, dtype: int64

In [ ]:
ourdata['Age'].sum()

119

In [ ]:
ourdata['Campus']

0    RUET
1     CoU
2     CoU
3     CoU
4     CoU
Name: Campus, dtype: object

In [ ]:
ourdata['Campus'].unique()

array(['RUET', 'CoU'], dtype=object)